media:
  input: static/assets
  output: /assets

content:
  - name: homepage
    label: Home Page
    type: file
    path: content/_index.md
    fields:
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
      - name: body
        label: Content
        type: rich-text

  - name: aktuelles
    label: Aktuelles
    type: collection
    path: content/aktuelles
    extension: md
    format: yaml-frontmatter
    exclude: ["_index.md"]
    view:
      title: title
      subtitle: date
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: slug
        label: Slug
        type: string
      - name: draft
        label: Draft
        type: boolean
      - name: body
        label: Content
        type: rich-text

  - name: vita
    label: Vita (CV Entries)
    type: file
    path: data/vita.yaml
    format: datagrid
    fields:
      - name: year
        label: Year/Period
        type: string
      - name: content
        label: Description
        type: text

  - name: publikationen
    label: Publikationen (Publications)
    type: file
    path: data/publications.yaml
    format: datagrid
    fields:
      - name: type
        label: Category
        type: string
      - name: content
        label: Publication Details
        type: text

  - name: forschungsprojekte
    label: Forschungsprojekte (Research Projects)
    type: file
    path: data/projects.yaml
    format: datagrid
    fields:
      - name: duration
        label: Duration
        type: string
      - name: description
        label: Description
        type: text
